language: node_js
node_js: node
cache:
  yarn: true
  directories:
  - node_modules
script:
- echo $GATSBY_MAPBOX_TOKEN
- yarn lint
- yarn test --coverage && yarn coveralls < ./coverage/lcov.info
before_deploy:
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  on:
    branch: master
env:
  global:
    secure: Ynia/vjOli8prAF43CskxQXKXN7MgjztrUNRUzSu3G3titsdBSPn0DisNeaDqGFx4yOn/sxkFmhZPmc78Sz4r5yZLNzYSKQc6y5YQ9Y6tHbh/+cNuynWzghoQmQFS1S5/tH/WyYZPT8RSiKRN1Gd2t4oS68nXEIRBe+yv7+ZmOk=
